# Generated by Django 2.2 on 2020-10-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinguser',
            name='voting_attempt',
            field=models.IntegerField(default=4),
        ),
    ]
