# Generated by Django 2.2 on 2020-10-30 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_votinguser_voting_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinguser',
            name='voting_attempt',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
