# Generated by Django 2.2 on 2020-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('King', 'King'), ('Queen', 'Queen')], default='King', max_length=5)),
                ('current_class', models.CharField(max_length=10)),
            ],
        ),
    ]
