# Generated by Django 2.2 on 2020-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_queen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstyear',
            name='img',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firstyear',
            name='current_class',
            field=models.CharField(help_text='(eg. 1CST-12,A ...)', max_length=10),
        ),
    ]
