# Generated by Django 2.2 on 2020-10-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_queen', '0003_auto_20201027_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstyear',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
