# Generated by Django 2.2 on 2020-10-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_queen', '0004_firstyear_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheWhole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='kingqueenIMG')),
                ('gender', models.CharField(choices=[('King', 'King'), ('Queen', 'Queen')], default='King', max_length=5)),
                ('current_class', models.CharField(help_text='(eg. 1CST-12,A ...)', max_length=10)),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
